server:
  port: 8081 #aplikasi berjalan di port 8081
  servlet:
    context-path: /user-management #localhost:8081/user-management

spring:
  cache:
    type: redis
    redis:
      time-to-live: 10m
  data:
    redis:
      host: localhost
      port: 6380
  application:
    name: usermanagementservice
  datasource: #CONFIG POSTGRES CONNECTION
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_management_batch_16
    username: postgres
    password: dimas
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #ngerapiin query sql di console
        show_sql: true #munculin query sql di console

#Ketika aplikasi nyala, report alamat ke http://localhost:8761/eureka/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
jwt:
  secret-key: ajhjsdghjasdgjhasgdhjqyuqetyqwvdmnasvdghjf
  expired-in: 900 # 900s atau 15 menit